#add/remove item in administration
#create unique name, set path pattern (id required?), choose template,
#choose API parameters, set SEO settings
#use unique name in template
#bum bum result is this routes.yaml file..
app_book:
  path: /book/{id<\d+>}-{slug?}
  defaults:
    template: 'book.html.twig'
    APIParameters:
      item:
        entity: 'Book'
        properties: ['imageSrc','isbn10','isbn13','description','pages','releasedYear','rating','format','language',]
        relations:
          awards:
            parameters:
              limit: 3
          characters:
            parameters:
              limit: 3
          genres:
            parameters:
              limit: 3
          persons:
            parameters:
              limit: 3
          places:
            parameters:
              limit: 3
          series:
            parameters:
              limit: 3
        methods:
          otherBooks:
            parameters:
              limit: 10
            properties: ['imageSrc']
    settings:
      default_image_file: 'book.png'
      external_images: true
      structured_data: 'book'
      title: 'Download &#128213; {{ #name }} {{ #authors[1].name }} {{ #releasedYear }}'
      title_options:
        delimiter: ' - '
        remove_delimiter_if_last: true
        #trim_on_word
        #allowed_html
        #ellipsis
      description: '&#128214; Read/download {{ #name }} {% &#11088;{{ rating.value }}/{{ #rating.scale }} %} {{ #authors[2].name }} {{ #genres[3].name }} {{ description[24] }}'
      #description_options:
      #  ellipsis: ' ..'