#add/remove item in administration
#create unique name, set path pattern (id required?), choose template,
#choose API parameters, set SEO settings
#use unique name in template
#bum bum result is this routes.yaml file..
app_book:
  path: /book/{id<\d+>}-{slug?}
  defaults:
    template: 'book.html.twig'
    APIParameters:
      item:
        entity: 'Book'
        properties: ['imageSrc','isbn10','isbn13','description','pages','releasedYear','rating','format','language',]
        relations:
          awards:
            parameters:
              limit: 3
          characters:
            parameters:
              limit: 3
          genres:
            parameters:
              limit: 3
          persons:
            parameters:
              limit: 3
          places:
            parameters:
              limit: 3
          series:
            parameters:
              limit: 3
        methods:
          - function: 'otherBooks'
            parameters:
              limit: 10
            properties: ['imageSrc']
    settings:
      default_image_file: 'book.png'
      external_images: true
      structured_data: 'book'
      title: "Download &#128213; {{ item.name|delimiter }} {{ arraySlice('1', item.persons, 'name')|delimiter }} {{ item.releasedYear }}"
      title_options:
        delimiter: ' - '
        remove_delimiter_if_last: true
        #renderIfEverythingSet('&#11088;%s/%s', {rating.value, rating.scale})|delimiter
        #{% &#11088;{{ rating.value }}/{{ #rating.scale }} %}
      description: "&#128214; Read/download {{ item.name|delimiter }} {{ arraySlice('2', item.persons, 'name')|delimiter }} {{ arraySlice('3', item.genres, 'name')|delimiter }} {{ trimOnWord('24', item.description)|delimiter }}"
      description_options:
        delimiter: '. '
        remove_delimiter_if_last: false
        ellipsis: ' ..'

